version: '3'
services:
  nightfly:
    container_name: nightfly
    build: ./nightfly
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - nightfly_db
      - gatekeeper
      - redis
    environment:
      DATABASE_HOST: nightfly_db
      DB_USER: nightfly
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_PASS: nightfly
      SPRING_PROFILES_ACTIVE: prod

  nightfly_db:
    container_name: nightfly_db
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: nightfly
      MARIADB_PASSWORD: nightfly
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: nightfly
    command: --default-storage-engine innodb
    restart: always
    volumes:
      - ./nightfly_db/data:/var/lib/mysql
      - ./nightfly_db/scripts:/docker-entrypoint-initdb.d

  gatekeeper:
    container_name: gatekeeper
    build: ./gatekeeper
    restart: on-failure
    ports:
      - 9000:9000
    environment:
      SPRING_PROFILES_ACTIVE: prod
  
  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis/data:/data
