services:
  nightfly:
    container_name: nightfly
    build: ./nightfly
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      nightfly_db:
        condition: service_healthy
        restart: true
      gatekeeper:
        condition: service_started
      redis:
        condition: service_started
    environment:
      DATABASE_HOST: nightfly_db
      DB_USER: nightfly
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_PASS: nightfly
      SPRING_PROFILES_ACTIVE: prod

  nightfly_db:
    container_name: nightfly_db
    image: mariadb:11.5
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: nightfly
      MARIADB_PASSWORD: nightfly
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: nightfly
    command: --default-storage-engine innodb
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./nightfly_db/data:/var/lib/mysql
      - ./nightfly_db/scripts:/docker-entrypoint-initdb.d
      - ./nightfly_db/config:/etc/mysql/mariadb.conf.d

  gate:
    container_name: gate
    build: ./gate
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      nightfly:
        condition: service_started
      gatekeeper:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod

  gatekeeper:
    container_name: gatekeeper
    build: ./gatekeeper
    restart: on-failure
    ports:
      - 9000:9000
    depends_on:
      gatekeeper_db:
        condition: service_healthy
        restart: true
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_HOST: gatekeeper_db
      DB_USER: gatekeeper
      DB_PASS: gatekeeper


  gatekeeper_db:
    container_name: gatekeeper_db
    image: mariadb:11.5
    ports:
      - 3307:3306
    environment:
      MARIADB_USER: gatekeeper
      MARIADB_PASSWORD: gatekeeper
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: gatekeeper
    command: --default-storage-engine innodb
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./gatekeeper_db/data:/var/lib/mysql
      - ./gatekeeper_db/scripts:/docker-entrypoint-initdb.d
      - ./gatekeeper_db/config:/etc/mysql/mariadb.conf.d
  
  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis/data:/data
