spring:
  web-application-type: none
  config:
    # Local development properties outside version control
    import: optional:classpath:local.yml
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://gatekeeper:9000
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://${DATABASE_HOST:localhost}:3306/nightfly
    username: ${DB_USER:nightfly}
    password: ${DB_PASS:nightfly}
  data:
    jdbc:
      dialect: org.hibernate.dialect.MariaDBDialect
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
cron:
  runner:
    enabled: false
supabase:
  url: ${SUPABASE_URL}
  anon: ${SUPABASE_ANON_KEY}
  jwt_secret: ${SUPABASE_JWT_SIGNER}
