cron:
  runner:
    enabled: true
spring:
  main:
    web-application-type: none
  config:
    # Local development properties outside version control
    import: optional:classpath:local.yml
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:nightfly;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=RUNSCRIPT FROM 'classpath:h2init.sql'
    username: sa
    password:
redis:
  host: localhost
  port: 6379
