spring:
  config:
    # Local development properties outside version control
    import: optional:classpath:local.yml
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:nightfly;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MariaDB
    username: sa
    password:
    hikari:
      allow-pool-suspension: true
  data:
    redis:
      lettuce:
        pool:
          enabled: false