logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.springframework.security: TRACE
spring:
  cache:
    type: simple
  config:
    # Local development properties outside version control
    import: optional:classpath:local.yml
  sql:
    init:
      mode: always
      schema-locations: classpath:h2schema.sql
      data-locations: classpath:h2data.sql
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:nightfly;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MariaDB;INIT=RUNSCRIPT FROM 'classpath:h2schema.sql'\;RUNSCRIPT FROM 'classpath:h2data.sql'
    url: jdbc:h2:mem:nightfly;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MariaDB;INIT=RUNSCRIPT FROM 'classpath:h2schema.sql'\;RUNSCRIPT FROM 'classpath:h2data.sql'
    username: sa
    password:
  data:
    redis:
      lettuce:
        pool:
          enabled: false
web:
  cors:
    allowedOrigins:
     - "http://127.0.0.1:5500"
     - "http://127.0.0.1:5000"
     - "http://127.0.0.1:3000"
    allowedMethods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    maxAge: 3600