server:
  port: 9090
spring:
  application:
    name: Gate
  threads:
    virtual:
      enabled: true
  config:
    # Local development properties outside version control
    import: optional:classpath:local.yml
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://gatekeeper:9000
        registration:
          nightfly:
            provider: spring
            client-id: nightfly
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: api.nightfly,openid,profile